---
- name: Import Worker certs
  include_tasks: import-certs.yaml
- name: Disable swap
  include_tasks: disable-swap.yaml
- name: Clean previous K8S install
  include_tasks: clean-previous-k8s-install.yaml
  when: ilke_base_components.kubernetes.upgrade | bool == True
- name: Setup Worker
  include_tasks: setup-worker.yaml
- name: Clear kubenetes components
  include_tasks: delete-k8s-components.yaml
  tags: ['never', 'uninstall']
- name: Clear Containerd and Docker components
  include_tasks: delete-containerd-docker-components.yaml
  tags: ['never', 'uninstall']
