---
#    msg: "Variable delete_previous_k8s_install is set to {{ delete_previous_k8s_install }} ! Supported values are : True, False"
#  when: (delete_previous_k8s_install | string) not in ['True','False']

- name: check rotate certificates
  fail:
    msg: "Rotate certificates {{ ilke_pki.management.rotate_certificats }} is not supported ! Supported values are : true, false"
  when: (ilke_pki.management.rotate_certificats| string| lower) not in ['true', 'false']

- name: check current Kubernetes release
  fail:
    msg: "Kubernetes release {{ ilke_base_components.kubernetes.upgrade }} is not supported ! Supported values are : true, false"
  when: (ilke_base_components.kubernetes.upgrade| string| lower) not in ['true', 'false']

- name: check external_loadbalancing
  fail:
    msg: "External_loadbalancing {{ ilke_network.external_loadbalancing.enabled }} is not supported ! Supported values are : true, false"
  when: (ilke_network.external_loadbalancing.enabled| string| lower) not in ['true', 'false']

- name: check OpenEBS Path
  fail:
    msg: "Path where OpenEBS store HostPath volumes on Pod node {{ ilke_features.storage.enabled }} is not supported ! Supported values are : true, false"
  when: (ilke_features.storage.enabled| string| lower) not in ['true', 'false']

- name: check Kubernetes dashboard
  fail:
    msg: "Kubernetes dashboard {{ ilke_features.dashboard.enabled }} is not supported ! Supported values are : true, false"
  when: (ilke_features.dashboard.enabled| string| lower) not in ['true', 'false']
- name: check default admin user
  fail:
    msg: "default admin user {{ ilke_features.dashboard.generate_admin_token }} is not supported ! Supported values are : true, false"
  when: (ilke_features.dashboard.generate_admin_token| string| lower) not in ['true', 'false']

- name: Metrics-Server
  fail:
    msg: "Metrics-Server {{ ilke_features.metrics_server.enabled }} is not supported ! Supported values are : true, false"
  when: (ilke_features.metrics_server.enabled| string| lower) not in ['true', 'false']

- name: check ETCD cluster
  fail:
    msg: "ETCD cluster {{ ilke_base_components.etcd.check }} is not supported ! Supported values are :  true, false"
  when: (ilke_base_components.etcd.check| string| lower) not in ['true', 'false']

- name: check ETCD cluster
  fail:
    msg: "ETCD cluster {{ ilke_base_components.etcd.backup.enabled }} is not supported ! Supported values are :  true, false"
  when: (ilke_base_components.etcd.backup.enabled| string| lower) not in ['true', 'false']

- name: chekck Monitoring
  fail:
    msg: "Enable Monitoring {{ ilke_features.monitoring.enabled }} is not supported ! Supported values are : true, false"
  when: (ilke_features.monitoring.enabled| string| lower) not in ['true', 'false']

- name: chekck Monitoring Data
  fail:
    msg: "Monitoring Data {{ ilke_features.monitoring.persistent }} is not supported ! Supported values are : true, false"
  when: (ilke_features.monitoring.persistent| string| lower) not in ['true', 'false']

- name: Check Populate /etc/hosts
  fail:
    msg: "Populate /etc/hosts variable is set to : {{ ilke_populate_etc_hosts }} ! Supported values are : true, false"
  when: (ilke_populate_etc_hosts| string| lower) not in ['true', 'false']

- name: Check runtime variable
  fail:
    msg: "Runtime {{ ilke_base_components.container.engine }} is not supported ! Supported values are : docker, containerd, none, false"
  when: (ilke_base_components.container.engine| string| lower) not in ['docker','containerd','false','none']

- name: Check CNI plugin used
  fail:
    msg: "CNI plugin used {{ ilke_network.cni_plugin }} is not supported ! Supported values are : calico, kube-router, none"
  when: (ilke_network.cni_plugin| string| lower) not in ['calico','kube-router','none']

- name: Check Kube-Proxy mode
  fail:
    msg: "Kube-Proxy mode {{ ilke_network.kube_proxy.mode }} is not supported ! Supported values are : ipvs, none, false"
  when: (ilke_network.kube_proxy.mode| string| lower) not in ['ipvs','false','none']

- name: Check Default ClusterIP loadBalancing Algorithm
  fail:
    msg: "Default ClusterIP loadBalancing Algorithm {{ ilke_network.kube_proxy.algorithm }} is not supported ! Supported values are : rr, lc, dh, sh, sed, nq, none"
  when: (ilke_network.kube_proxy.algorithm| string| lower) not in ['rr','lc','dh','sh','sed','nq','none']

- name: Check Jiva FS types
  fail:
    msg: "Jiva FS types {{ ilke_features.storage.jiva.fs_type }} is not supported ! Supported values are : ext4, none, false"
  when: (ilke_features.storage.jiva.fs_type| string| lower) not in ['ext4','false','none']

- name: check Ingress Controller
  fail:
    msg: "Ingress Controller {{ ilke_features.ingress.controller }} is not supported ! Supported values are : none, traefik, haproxy, nginx"
  when: (ilke_features.ingress.controller| string| lower) not in ['none','traefik','haproxy','nginx']

- name: Check cluster_cidr
  fail:
    msg: "Variable cluster_cidr must be an IP adresse CIDR !"
  when: ilke_network.cidr.service is not regex("^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$")

- name: Check service_cluster_ip_range
  fail:
    msg: "Variable service_cluster_ip_range must be an IP adresse CIDR !"
  when: ilke_network.external_loadbalancing.ip_range  | ipaddr('10.10.20.0/24') 
  #fail:
   # msg: "Variable service_cluster_ip_range must be an IP adresse CIDR !"
  #when: ilke_network.external_loadbalancing.ip_range| ipaddr('10.10.20.0/24')
  #when: ilke_network.external_loadbalancing.ip_range is not regex("^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$")

- name: Check kubernetes_service
  fail:
    msg: "ilke_network.service_ip.kubernetes must be an IP adresse from service_cluster_ip_range !"
  when: ilke_network.service_ip.kubernetes is not regex("^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$")

- name: Check cluster_dns_ip
  fail:
    msg: "ilke_network.service_ip.corednsmust be an IP adresse from service_cluster_ip_range "
  when: ilke_network.service_ip.coredns is not regex("^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$")

- name: Check Node Port Range
  fail:
    msg: "Variable must be INT-INT => sample : 30000-32767"
  when: ilke_network.nodeport.range is not regex("(?:[+-]?(?:[0-9]+))-(?:[+-]?(?:[0-9]+))")

- name: Check data_path variable
  fail:
    msg: "Variable data_path must be a linux path ! Get {{ data_path }}"
  when: ilke.global.data_path is not regex("^(\/[^\/ ]*)+\/?$")

- name : check kubernetes release
  fail:
    msg: "kubernetes release {{ ilke_base_components.kubernetes.release }} is not supported ! Supported values are : v1.20.4"
  when: (ilke_base_components.kubernetes.release) is version('v1.20.5', strict=False)

#- name: check Ingress controller release
 # fail:
  #  msg: "Ingress controller release {{ ilke_features.ingress.release }} is not supported ! Supported values are : true, false"
  #when: (ilke_features.ingress.release| string| lower) not in ['true', 'false']