---
- name: Make sure Reloader is installed
  include_tasks: reloader.yaml

- name: Create tempdir
  tempfile:
    state: directory
    suffix: logrotate
  register: logrotate_tempdir
  changed_when: false

- name: Render templates
  template:
    dest: "{{ logrotate_tempdir.path }}/logrotate.yaml"
    src: "logrotate.yaml.j2"
  changed_when: false

- name: Apply templates
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf apply -f {{ logrotate_tempdir.path }}/logrotate.yaml
  register: apply_logrotate
  changed_when: >
    apply_logrotate.stdout is search("created")
    or apply_logrotate.stdout is search("configured")
- name: Cleanup tempdir
  file:
    state: absent
    path: "{{ logrotate_tempdir.path }}"
  changed_when: false
