---
- name: Create tempdir
  tempfile:
    state: directory
    suffix: reloader
  register: reloader_tempdir
  changed_when: false

- name: Render templates
  template:
    dest: "{{ reloader_tempdir.path }}/reloader.yaml"
    src: "reloader.yaml.j2"
  changed_when: false

- name: Apply templates
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf apply -f {{ reloader_tempdir.path }}/reloader.yaml
  register: apply_reloader
  changed_when: >
    apply_reloader.stdout is search("created")
    or apply_reloader.stdout is search("configured")
- name: Cleanup tempdir
  file:
    state: absent
    path: "{{ reloader_tempdir.path }}"
  changed_when: false

- name: Verify if reloader pod has successfully started
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf get deploy -n kube-system reloader-reloader
  changed_when: false
  register: reloader_deployment
  until: reloader_deployment.stdout.find("1/1") != -1
  retries: 300
  delay: 10
  run_once: true
