name: ansible-lint-ilke

on:
  pull_request:
    branches: 
      - master
      - core

jobs:
  ansible_lint:
    runs-on: ubuntu-latest
    name: A job to lint Ansible Playbooks and roles for ILKE
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: test ansible lint
      uses: ./actions/ansible-lint
